### PR TITLE
Added summary of responses

### LINKED ISSUE #11: Display summary of responses before submission
User could have second thoughts about how s/he responded to one of the questions especially after a second glance at what the user entered earlier prompting the user to want to update their response. If the user is able to see the entire summary of answers provided, then the user can probably revisit and change. So the summary page just allows you to confirm your answers before final submission, similar to job application systems which permits to verify your answers are accurate before final submission.

Cc: @NathanBaleeta

### PR DESCRIPTION
**Pull request by rachita19082**
Fix #11 
The new component summary.js has been added and modifications have been made to the review.js to display the summary page after all questions are answered.

### CODE REVIEW

**Comment by rachita19082** [comment]
@lacabra I am still working on this pull request, I made this PR so that you can see the current progress and correct me early on if I am making any errors. Please take a look and let me know if I should make any changes. The buttons are not functional yet and I am working on improving the style. 

This seems like a trivial question but I am unable to figure out how to align the `Modify Response` buttons to the right. I tried using `float-right` classname in the Button tag but it makes the button overlap with the text below.

**Comment by rachita19082** [comment]
@lacabra I have updated the code. The only thing remaining is to implement the functionality to display the modified responses in summary. Only a few design improvements and error handling will be left after that.

**Comment by rachita19082** [comment]
@lacabra All functionality has been implemented. Only some styling changes, basic error handling and documentation is remaining. Please review and let me know if there are any changes.

**Comment by rachita19082** [comment]
@lacabra In commit 36c7b5b, I have resolved an existing bug in the code. 
While adding error handling, I came across a bug. If someone drags the confidence slider once and brings it back to the `choose` position, an error message is not displayed. The reason for this is in the RangeSlider tag `onChange={(changeEvent) => setConfidence(changeEvent.target.value)}`. The value of `changeEvent.target.value` is a string, so the confidence is set to "3". Subsequently in the `handleClick(next)` function, when we check if `confidence === DEFAULT_CONFIDENCE` it returns false since the value of DEFAULT_CONFIDENCE is integer 3. Thus, an error is not displayed. I corrected it by replacing the code with `onChange={(changeEvent) => setConfidence(parseInt(changeEvent.target.value, 10))}` to explicitly convert the value to an integer.

**Review by lacabra — CHANGES_REQUESTED** [review]
Thanks @rachita19082 for this contribution, it looks really good! 💪
I very much appreciate your several requests for input (I apologize for not being as responsive as I would like, since these occurred mostly over the weekend).

The one change request I have is to adjust the progress bar at the bottom, since because you added one more screen, at the very last step it displays more than 100%. Can you make the necessary change?

See the bottom of the screenshot below (120%):
Screen Shot 2021-05-03 at 2 13 38 PM (3)

**Comment by rachita19082** [comment]
@lacabra  Understood, I will make the required changes. Let me know if anything else is required.

**Comment by rachita19082** [comment]
@lacabra I have made the necessary changes. I'd be happy to incorporate any other changes if needed.

**Review by lacabra — APPROVED** [review]
Thanks @rachita19082 for promptly addressing the requested change. This looks very good to me, thanks again!

**Pull request merged**
