### PR TITLE
Small bug in href url

### PR DESCRIPTION
**Pull request by vaishnavi-ch**
modified the href link as it outputs '404 page not found' instead of actual repository

### CODE REVIEW

**Review by lacabra — CHANGES_REQUESTED** [review]
Again, good catch; thanks @vaishnavi-ch!

Similarly to #23, the formatter is failing in the CI, would you mind fixing it?

**Comment by vaishnavi-ch** [comment]
@lacabra   
The linter showed this error but I didnt understand it
326:11  error  Replace `·href={`https://github.com/${refOwner}/${repo}`}·target="_blank"·rel="noreferrer"` with `⏎··········href={`https://github.com/${refOwner}/${repo}`}⏎··········target="_blank"⏎··········rel="noreferrer"⏎········`  prettier/prettier

shall I try changing the href to {"https://github.com/"+refOwner+"/"+repo}?

**Comment by lacabra** [comment]
@vaishnavi-ch: there is nothing wrong with the code itself, just the style in which it is coded. Long story short, if you run `npm run linter:fix` will fix it for you. You can typically find this information in `package.json` like [here](https://github.com/lacabra/validate-digitalpublicgoods/blob/3ed81e28ce5dc46f96390803a90dc551d1532d89/package.json#L13).

What the error is saying is that instead of coding like this:
```
        <a href={`https://github.com/${refOwner}/${repo}`} target="_blank" rel="noreferrer">
```
the linter expects instead something like this:
```
        <a
          href={`https://github.com/${refOwner}/${repo}`}
          target="_blank"
          rel="noreferrer"
        >
```

**Comment by vaishnavi-ch** [comment]
Thank you, I've understood it now!

**Review by lacabra — APPROVED** [review]
Thanks @vaishnavi-ch for your prompt response in addressing the requested changed, this looks good to me now 💪

**Pull request merged**
